package: 
  name: amc_carrier_core
  version: {{ GIT_DESCRIBE_TAG }}

source:
   path: ..

build:
   number: {{ GIT_DESCRIBE_NUMBER|int }}

requirements:
   build:
     - python
     - rogue
     - git
     - gitpython
     - numpy

   run:
     - python
     - rogue
     - numpy

about:
   home: https://github.com/slaclab/lcls2-pgp-fw-lib
   license: SLAC Open License
   license_file: LICENSE.txt
   summary: AMC Carrier Core Firmware Library

